### ISSUE TITLE
Question: Still active?

### ISSUE THREAD

**Issue by asamuzaK** [danburzo/selery#10]
selery seems to have a lot of potential.
But it hasn't been updated in a long time, is it still an active repository?

Thanks.

**Comment by danburzo** [comment]
The project is currently dormant but not archived. It's something I want to finish implementing eventually

**Comment by asamuzaK** [comment]
Glad to hear that selery hasn't been archived yet.

I ask this question because selery seems like a better replacement for the CSS Selectors library than the one jsdom currently depends on.

Let's start developing selery again?

**Comment by danburzo** [comment]
I really appreciate the interest in the development of this library. You're right, selery was meant to work, among other things, as a replacement for the CSS selector library in jsdom, but it's still a long way from that. 

At the moment I'm afraid the core of the library is not sufficiently clarified to allow collaborative development (you'll notice a sizeable refactor stuck in a pull request), and I'm not able to steer the project for the time being.

If you find the code useful in its current form, the best course of action, realistically, is to grab it as a starting point for a new library. You'll also find more mature alternatives in the [See also](https://github.com/danburzo/selery#see-also) section.

**Comment by asamuzaK** [comment]
Got it.

Thanks
